---
db:
  driver: sqlite
  encryption:
    keyFile: "./encryption/unittest.key"
  blockQueries: true
  logQueries: true
  postgres:
    host: "localhost"
    database: "kyma"
    port: 5432
    user: kyma
    password: kyma
    useSsl: false
  sqlite:
    file: "test/unittest.db"
    deploySchema: true
    resetDatabase: true
mothership:
  scheme: http
  host: localhost
  port: 8080
  scheduler:
    reconcilers:
      base:
        url: "http://localhost:8081/v1/run"
    preComponents:
      - cluster-essentials
      - istio-configuration
      - certificates
